# Generated by Django 4.2.5 on 2023-09-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_category_slug_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='qw', max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='qw', max_length=255, verbose_name='URL'),
        ),
    ]
